version: '3'

services:
  web:
    image: nginx:alpine
    container_name: web
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build: ./docker
    container_name: php
    working_dir: /var/www/
    user: dev:dev
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data/:/var/lib/postgresql/data:rw

  adminer:
    image: adminer
    container_name: adminer
    environment:
      ADMINER_DESIGN: konya
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8080:8080"

  #memcached:
  #  image: memcached:latest
  #  ports:
  #    - 11211:11211
  #  command: -m 64

